[package]
name = "rust-cleanup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-cleanup"
test = false
bench = false

[dependencies]
# walkdir = "2"  # For traversing directories
# inquire = "0.6" # For interactive prompts

walkdir = "2" 
clap = "4"
# clap = { version = "4", features = ["derive"] } # For command line argument parsing
